name: Auto-bump
on:
  schedule:
    - cron: '0 6 * * *'
  workflow_dispatch:

jobs:
  bump:
    runs-on: macos-26
    permissions:
      contents: write
      pull-requests: write
    steps:
      - uses: actions/checkout@v7
      - uses: Homebrew/actions/setup-homebrew@main
      - uses: Homebrew/actions/bump-packages@main
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          formulae: fleetctl
          fork: false
